export enum Titled {
  'GRAND_MASTER' = 'GM',
  'WOMAN_GRAND_MASTER' = 'WGM',
  'INTERNATIONAL_MASTER' = 'IM',
  'WOMAN_INTERNATIONAL_MASTER' = 'WIM',
  'FIDE_MASTER' = 'FM',
  'WOMAN_FIDE_MASTER' = 'WFM',
  'NATIONAL_MASTER' = 'NM',
  'WOMAN_NATIONAL_MASTER' = 'WNM',
  'CANDIDATE_MASTER' = 'CM',
  'WOMAN_CANDIDATE_MASTER' = 'WCM',
}
